[package]
name = "threshold_touch_id"
type = "contract"
authors = [""]
compiler_version = "0.16.0"

[dependencies]
# Framework import
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.8.9", directory = "yarn-project/aztec-nr/aztec" }

# Utility dependencies
value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.8.9", directory = "yarn-project/aztec-nr/value-note" }
safe_math = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.8.9", directory = "yarn-project/aztec-nr/safe-math" }
