[package]
name = "threshold_touch_id"
type = "contract"
authors = ["colinnielsen"]
compiler_version = ">=0.17.0"

[dependencies]
# Framework import
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.14.2", directory = "yarn-project/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.14.2", directory = "yarn-project/aztec-nr/authwit" }

# Utility dependencies
value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.14.2", directory = "yarn-project/aztec-nr/value-note" }
safe_math = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.14.2", directory = "yarn-project/aztec-nr/safe-math" }
